# Tox (https://tox.wiki/) configuration file.
# To use it, run "tox" from this directory.
#
# For a specific environment, run:
#   "tox -e <env>" (i.e.: "tox -e test")

[tox]
envlist =
    lint
    test


[testenv:lint]
description = run linter and formatter
skip_install = true
dependency_groups =
    lint
commands =
    # validate project configuration
    validate-pyproject pyproject.toml
    # run ruff linting
    ruff check --fix --show-fixes --exit-non-zero-on-fix .
    # run ruff formatting
    ruff format --exit-non-zero-on-format .


[testenv:test]
description = run tests
passenv = *
commands =
    pytest {tty:--color=yes} {posargs:.}
